---
name: Java CI

on: [push, pull_request]
env:
  java_reference_version: 11
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        java: [11, 15]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}
    environment: coverage # open environment, no critical secrets
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 25
      - name: Set version environment for version string
        run: |
          export REV=${GITHUB_REF#refs/*/}
          echo "REVISION=${REV/\//-}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF#refs/tags/}" =~ ^${{java_reference_version}}\.[0-9]*\.[0-9]*$ ]]; then
            echo "CHANGELIST=" >> $GITHUB_ENV
          else
            echo "CHANGELIST=-SNAPSHOT" >> $GITHUB_ENV
          fi
          echo "github ref: ${GITHUB_REF}"
          echo "setting env:"
          cat ${GITHUB_ENV}
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        run: mvn -Dgpg.skip=true --no-transfer-progress --batch-mode -Drevision=${REVISION} -Dchangelist=${CHANGELIST} package
      - name: CodeCov coverage Reporter
        uses: codecov/codecov-action@v1
        if: matrix.java == java_reference_version
      - name: Codacy coverage Reporter
        if: matrix.java == java_reference_version
        uses: codacy/codacy-coverage-reporter-action@0.2.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: Run Codacy Analysis CLI
        if: matrix.java == java_reference_version
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will handover control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      - name: Upload SARIF results file
        if: matrix.java == java_reference_version
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif

  publish:
    name: Deploy to github packages and Sonatype OSSRH
    needs: test
    runs-on: ubuntu-18.04
    environment: deploy
    steps:
      - uses: actions/checkout@v2
      - name: Set version environment for version string
        run: |
          export REV=${GITHUB_REF#refs/*/}
          echo "REVISION=${REV/\//-}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF#refs/tags/}" =~ ^${{java_reference_version}}\.[0-9]*\.[0-9]*$ ]]; then
            echo "CHANGELIST=" >> $GITHUB_ENV
          else
            echo "CHANGELIST=-SNAPSHOT" >> $GITHUB_ENV
          fi
          echo "github ref: ${GITHUB_REF}"
          echo "setting env:"
          cat ${GITHUB_ENV}
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up the JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ test.java_reference_version }}
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: GPG_PASS
      - name: Deploy to Github Packages
        run: if [ -z "$CHANGELIST" ]; then mvn -DskipTests --no-transfer-progress --batch-mode -Drevision=${REVISION} -Dchangelist=${CHANGELIST} -Drelease=github deploy; fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASS: ${{ secrets.GPG_PASSPHRASE }}
      - name: Set up JDK to publish to OSSRH
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ test.java_reference_version }}
          server-id: ossrh
          server-username: SONATYPE_USER
          server-password: SONATYPE_PASS
          # gpg-private-key: ${{ secrets.GPG_KEY }} # gpg key was already added in the first java-setup phase, will fail the cleanup if added again
          gpg-passphrase: GPG_PASS
      - name: Deploy to Maven Central
        run: mvn -DskipTests --no-transfer-progress --batch-mode -Drevision=${REVISION} -Dchangelist=${CHANGELIST} -Drelease=ossrh deploy
        env:
          GPG_PASS: ${{ secrets.GPG_PASSPHRASE }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          SONATYPE_PASS: ${{ secrets.SONATYPE_PASS }}

...
